E_CLASSROOM-215-FE/BE-Profile-Edit-Function - first commit
framgia/sph-classroom-els-be pull request #44
Opened 2022-01-24 03:39 UTC by CaneteJoash

### Issue Link

### Definition of Done
- [] 
- [] 

### Commands to Run

### Notes
#### Main note
- 
#### Pages Affected
- 

#### Scenarios/ Test Cases
- [] it should `expected behavior` when `condition` 

### Screenshots

2022-01-27 02:30 UTC, catampongan commented
## Approved PR #44 
- [x] Able to change name
- [x] Display validation when password or email is incorrect

------

![name-change](https://user-images.githubusercontent.com/89382692/151281107-92512e5f-9cb2-4161-b867-64ff6350d6a8.gif)

------

- Total Test Time: 0.25 hr
- Total Iterations: 0
- Total Comments: 0

2022-01-27 03:28 UTC, karlolee50 commented on app/Http/Requests/Auth/ChangeNameEmailRequest.php
> +}
Is it possible to reuse the existing rules for email checking?

2022-01-27 03:32 UTC, karlolee50 commented on app/Http/Requests/Auth/UploadImageRequest.php
> +            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:1000',
```suggestion
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:1024',
```

2022-01-27 03:34 UTC, karlolee50 requested changes
Is it possible to delete the image files? These will be included in the develop branch if we merge this PR

![image](https://user-images.githubusercontent.com/26341975/151287370-83dcc4f4-3bc1-403a-876a-9803d53e5f08.png)

2022-01-28 02:19 UTC, karlolee50 approved these changes
Review time: 15 minutes
Comment/s: 2

2022-01-28 02:20 UTC, merged