E_CLASSROOM-255 [FE/BE] Implement adding a new quiz
framgia/sph-classroom-els-be pull request #50
Opened 2022-02-14 10:46 UTC by ErickDoroy

### Issue Link
- https://framgiaph.backlog.com/view/E_CLASSROOM-255

### Definition of Done
- [] 
- [] 

### Commands to Run

### Notes
#### Main note
- 
#### Pages Affected
- 

#### Scenarios/ Test Cases
- N/A

### Screenshots

2022-02-16 05:21 UTC, CaneteJoash commented
### Working 

- [x] Able to add quiz in the admin side.
- [x] Modal will popup when user clicks on "Add Quiz" button.
- [x] Modal will Close after the user add a new quiz.
- [x] Able to add the new quiz in the database. 

![SUCCESS](https://user-images.githubusercontent.com/89382909/154200292-1dab810c-9343-4b45-958e-1a6fe80244f1.gif)

-------------
-------------

### Comment/s

- [ ] Please fix the 'Add a Quiz' font weight. refer this in figma.

### figma
![image](https://user-images.githubusercontent.com/89382909/154200359-e862df91-bf78-4c0c-acbd-0552cdc41542.png)

### APP
![image](https://user-images.githubusercontent.com/89382909/154200167-70f4d49d-29f3-4915-97bb-17eee1847d6d.png)

- [ ] When we click the 'Go Back' button, the user must redirect to 'quizzes' not to the 'categories'.

![error should not redirect to categories](https://user-images.githubusercontent.com/89382909/154200695-838286db-4b16-4e8a-b356-71cab5f3ef33.gif)

- [ ] After clicking the 'Add Quiz' button the new quiz must automatically display in the list of quizzes.

![error should display the new quiz in the table](https://user-images.githubusercontent.com/89382909/154200835-a04657b1-696a-40b5-b471-fa670afe1df9.gif)

- [ ] Please fix the components, When we try to minimized the text input in the 'Instruction', the button bellow will push downwards. Refer my record. 

![error please fix the components](https://user-images.githubusercontent.com/89382909/154201044-3d0b36dc-d6c8-4b41-b3fd-d440b711104e.gif)

-----------
Total testing hr. 1.5 hr.

2022-02-16 09:08 UTC, karlolee50 commented on app/Http/Controllers/API/v1/Quiz/QuizController.php
> +    public function adminAdd(StoreQuizRequest $request)
change the function name because adminAdd is too generic

2022-02-16 09:08 UTC, karlolee50 commented on routes/api.php
> +        Route::post('/admin_add', [QuizController::class, 'adminAdd']);
change the route as well. since admin_add is too generic.

2022-02-16 09:08 UTC, karlolee50 requested changes
Review time: 10 minutes
Comment/s: 2

2022-02-18 06:16 UTC, catampongan commented
## Approved PR #50 
- [x] Able to add quiz in the admin side.
- [x] Able to add the new quiz in the database. 

--------------
![image](https://user-images.githubusercontent.com/89382909/154202481-6da33d45-414b-419d-a372-17e6737a99b0.png)

-----------
- Total Test Time: 1.5 hr
- Total Iterations: 0
- Total Comments: 0

2022-02-18 06:26 UTC, karlolee50 approved these changes

2022-02-18 06:49 UTC, merged